// Code generated by "stringer -type=Sender"; DO NOT EDIT.

package gogenerate

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Kafka-0]
	_ = x[Etcd-1]
	_ = x[File-2]
	_ = x[Bytes-3]
}

const _Sender_name = "KafkaEtcdFileBytes"

var _Sender_index = [...]uint8{0, 5, 9, 13, 18}

func (i Sender) String() string {
	if i < 0 || i >= Sender(len(_Sender_index)-1) {
		return "Sender(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Sender_name[_Sender_index[i]:_Sender_index[i+1]]
}
