// Code generated by "stringer -type FoodType"; DO NOT EDIT.

package simple_factory

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AppleType-0]
	_ = x[MeatType-1]
}

const _FoodType_name = "AppleTypeMeatType"

var _FoodType_index = [...]uint8{0, 9, 17}

func (i FoodType) String() string {
	if i < 0 || i >= FoodType(len(_FoodType_index)-1) {
		return "FoodType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FoodType_name[_FoodType_index[i]:_FoodType_index[i+1]]
}
